version: '3'
services:


  backend:
    build: backend
    ports:
      - "8080:8080"  # Expose Go backend on host port 8080
    depends_on:
      - redis

    
  redis:
    build: redis
    ports:
      - "6379:6379"
    volumes:
      - .redis:/redis


