# Use the official Go image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app/backend

# Copy the Go module files
COPY go.mod go.sum ./

# Download and cache the Go dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go application
RUN go build -o main .

# Command to run the Go application
CMD ["./main"]
